### ISSUE TITLE
Integrate script.js

### ISSUE THREAD

**Issue by d4t4king** [wkitty42/GAR#7]
If pertinent, integrate the custom `script.js` into the core SWE JS code.

**Comment by wkitty42** [comment]
script.js is not used in GAR any more AFAIK... what might have been used from there is now inside the cgi files that would have used it... those being gar.cgi and garipblock.cgi IIRC...

will leave this open until further code digging and confirmation that no routines from script.js are used...

**Comment by d4t4king** [comment]
Looks like this has already bee removed.
